# File: .aliases
alias cfg="git --git-dir=$HOME/.cfg --work-tree=$HOME"
alias ls="ls --color=auto"
alias ll="ls --color=auto -al"
alias llt="ls --color=auto -alt"
alias tma="tmux attach || tmux"
alias tmk="tmux kill-server"
alias fd="fdfind"
alias vim="nvim"
alias mux="tmuxinator"
