" File: vimrc

""" Visual Config 
" Enables relative line numbers
set relativenumber
set nu

" Enables syntax highlighting
if has ('syntax')
    syntax on
endif

""" Editor Behavior 
" Configures editor to use spaces
set expandtab

" Makes tab press equal four spaces
set tabstop=4
set shiftwidth=4
set softtabstop=5

" Handles autoindenting for new lines
set autoindent

""" Hotkeys 
" Binds F1 to clear highlight 
nnoremap <F1> :noh<return><esc>

" Source: https://www.reddit.com/r/neovim/comments/12zjmn1/how_to_include_parts_of_my_old_vim_config_in_nvim/
" Binds f12 to alternate between tabsd and spaces
" Allow toggling between tabs and spaces
function TabToggle()
    if &expandtab           " Use Tabs
        echo "Editor switched to tabs"
        set noexpandtab     " Always uses tabs instead of space characters (:noet).
        set softtabstop=0
    else                    " Use Spaces
        echo "Editor switched to spaced"
        set expandtab       " Always uses spaces instead of tab characters (:et).
        set softtabstop=4   " Causes <Tab> and <BS> to insert and delete the correct number of spaces. 
        " When 0, feature is off (:sts). Enable when using spaces.
    endif
endfunction
nmap <F12> mz:execute TabToggle()<CR>'z
